# judge0.conf
JUDGE0_TELEMETRY_ENABLE=false
ENABLE_WAIT_RESULT=true
USE_DOCS_AS_HOMEPAGE=true

REDIS_HOST=judge0-redis
REDIS_PASSWORD=judge0_redis_password

POSTGRES_HOST=judge0-db
POSTGRES_DB=judge0
POSTGRES_USER=judge0
POSTGRES_PASSWORD=judge0_postgres_password

CPU_TIME_LIMIT=10
MAX_CPU_TIME_LIMIT=15
WALL_TIME_LIMIT=15
MAX_WALL_TIME_LIMIT=20
MEMORY_LIMIT=262144
MAX_MEMORY_LIMIT=512000

ALLOW_ENABLE_NETWORK=false
ENABLE_NETWORK=false
